import type { EntityData, GraphEdge } from '@/types/graph';

export const DEFAULT_NODES: EntityData[] = [
  {
    id: 'core',
    label: 'SOC Core',
    kind: 'core',
    val: 24,
    color: '#0f172a',
    status: 'Operational',
    detail: 'Central IoT Threat Command Kernel. Orchestrates network-wide telemetry, coordinates AI security sentinels, and executes threat containment.',
    metadata: { tier: 'L0', role: 'Root Orchestrator', cluster: 'us-east-core-1' },
  },

  // Pillars
  {
    id: 'industrial-ot',
    label: 'Industrial OT',
    kind: 'pillar',
    val: 18,
    color: '#7c3aed',
    status: 'Protected',
    detail: 'SCADA & OT defense layer. Monitors factory floor sensors, Modbus/OPC-UA protocols, and PLC integrity.',
    metadata: { protocol: 'Modbus / OPC-UA', activeZones: 14 },
  },
  {
    id: 'smart-bldg',
    label: 'Smart Buildings',
    kind: 'pillar',
    val: 18,
    color: '#0284c7',
    status: 'Monitored',
    detail: 'Building Management System (BMS) security. Safeguards IP cameras, HVAC sensors, and access control.',
    metadata: { protocol: 'BACnet / Zigbee', managedDevices: 340 },
  },
  {
    id: 'net-edge',
    label: 'Network Edge',
    kind: 'pillar',
    val: 18,
    color: '#059669',
    status: 'Active Defense',
    detail: '5G Gateway & perimeter firewall. Manages Deep Packet Inspection and secure over-the-air firmware streams.',
    metadata: { throughput: '4.2 Gbps', packetInspection: 'Enabled' },
  },
  {
    id: 'health-iomt',
    label: 'Connected Health',
    kind: 'pillar',
    val: 18,
    color: '#e11d48',
    status: 'HIPAA Encrypted',
    detail: 'Internet of Medical Things (IoMT) security. Cryptographic integrity for patient monitors and infusion pumps.',
    metadata: { compliance: 'HIPAA Tier-1', activeEncryptions: 88 },
  },
  {
    id: 'automotive-v2x',
    label: 'Automotive V2X',
    kind: 'pillar',
    val: 18,
    color: '#d97706',
    status: 'Shield Live',
    detail: 'Vehicle-to-Everything telematics security. Shields in-vehicle CAN bus and ECU controllers from exploits.',
    metadata: { standard: 'ISO 21434', canShields: 'Active' },
  },

  // Agents & Enforcers
  {
    id: 'anomaly-ai',
    label: 'Anomaly AI',
    kind: 'agent',
    val: 12,
    color: '#0284c7',
    status: 'Scanning (120k pps)',
    detail: 'Machine learning model inspecting OT packet flows for anomalous payload signatures.',
  },
  {
    id: 'plc-audit',
    label: 'PLC Audit',
    kind: 'task',
    val: 10,
    color: '#64748b',
    status: 'Running',
    detail: 'Continuous ladder-logic checksum validation to detect unauthorized PLC modifications.',
  },
  {
    id: 'ot-eng',
    label: 'OT Security Lead',
    kind: 'human',
    val: 12,
    color: '#d97706',
    status: 'On-Call (Tier 3)',
    detail: 'Human OT security engineer authorized to issue physical air-gap isolations.',
  },

  {
    id: 'tamper-ai',
    label: 'Tamper AI',
    kind: 'agent',
    val: 12,
    color: '#0284c7',
    status: 'Armed',
    detail: 'Optical and physical enclosure sensor agent detecting physical enclosure opening.',
  },
  {
    id: 'port-scan',
    label: 'Port Scanner',
    kind: 'task',
    val: 10,
    color: '#64748b',
    status: 'Scheduled',
    detail: 'Automated network scan identifying unauthenticated rogue Wi-Fi/Bluetooth IoT nodes.',
  },
  {
    id: 'zero-trust',
    label: 'Zero Trust Enforcer',
    kind: 'agent',
    val: 12,
    color: '#0284c7',
    status: 'Active Enforcer',
    detail: 'Dynamically authenticates IoT device certificates and isolates untrusted MAC addresses.',
  },

  {
    id: 'firmware-ai',
    label: 'Firmware AI',
    kind: 'agent',
    val: 12,
    color: '#0284c7',
    status: 'Analyzing',
    detail: 'Cross-references edge device firmware binaries against the NIST NVD database.',
  },
  {
    id: 'ota-patch',
    label: 'OTA Patch Pipeline',
    kind: 'task',
    val: 10,
    color: '#64748b',
    status: 'Queued',
    detail: 'Cryptographically signed firmware deployment pipeline targeting gateway clusters.',
  },
  {
    id: 'pcap-stream',
    label: 'PCAP Streamer',
    kind: 'task',
    val: 10,
    color: '#64748b',
    status: 'Recording',
    detail: 'Full packet capture and real-time protocol breakdown for suspicious edge gateway traffic.',
  },

  {
    id: 'pki-sentinel',
    label: 'PKI Sentinel',
    kind: 'agent',
    val: 12,
    color: '#0284c7',
    status: 'Keys Synced',
    detail: 'Manages automated mTLS X.509 certificate issuance and short-lived key rotation.',
  },
  {
    id: 'mqtt-audit',
    label: 'MQTT Auditor',
    kind: 'task',
    val: 10,
    color: '#64748b',
    status: 'Passing',
    detail: 'Validates encrypted MQTT topic subscriptions and rate-limits publish bursts.',
  },

  {
    id: 'can-bus-ai',
    label: 'CAN Bus AI',
    kind: 'agent',
    val: 12,
    color: '#0284c7',
    status: 'Shield Active',
    detail: 'In-vehicle IPS filtering spoofed CAN arbitration IDs and blocking injection.',
  },
  {
    id: 'isolation-killswitch',
    label: 'Isolation Task',
    kind: 'task',
    val: 10,
    color: '#64748b',
    status: 'Standby',
    detail: 'Instant network kill-switch task that drops BGP routes for compromised nodes.',
  },
  {
    id: 'soc-analyst',
    label: 'SOC Analyst',
    kind: 'human',
    val: 12,
    color: '#d97706',
    status: 'Active Monitor',
    detail: 'Cybersecurity Operations Center analyst reviewing correlated IoT threat vectors.',
  },

  // Tools & Integrations
  {
    id: 'wireshark',
    label: 'Wireshark Engine',
    kind: 'tool',
    val: 8,
    color: '#e11d48',
    status: 'Connected',
    detail: 'Captures raw 802.15.4, Zigbee, and Ethernet frames for forensic inspection.',
  },
  {
    id: 'shodan',
    label: 'Shodan API',
    kind: 'tool',
    val: 8,
    color: '#e11d48',
    status: 'Connected',
    detail: 'Attack surface monitoring feeding exposure data for public IoT IPs.',
  },
  {
    id: 'suricata',
    label: 'Suricata IDS',
    kind: 'tool',
    val: 8,
    color: '#e11d48',
    status: 'Connected',
    detail: 'High-speed network threat detection engine matching signature rules.',
  },
  {
    id: 'vault',
    label: 'HashiCorp Vault',
    kind: 'tool',
    val: 8,
    color: '#e11d48',
    status: 'Connected',
    detail: 'Centralized secrets manager and PKI root CA for signing device firmware.',
  },
  {
    id: 'zeek',
    label: 'Zeek Monitor',
    kind: 'tool',
    val: 8,
    color: '#e11d48',
    status: 'Connected',
    detail: 'Translates raw network traffic into structured behavioral security logs.',
  },
  {
    id: 'kibana',
    label: 'Kibana SIEM',
    kind: 'tool',
    val: 8,
    color: '#e11d48',
    status: 'Connected',
    detail: 'Real-time SIEM dashboard for incident correlation and alert aggregation.',
  },
];

export const DEFAULT_EDGES: GraphEdge[] = [
  // Core to Pillars
  { source: 'core', target: 'industrial-ot', relType: 'COMMANDS' },
  { source: 'core', target: 'smart-bldg', relType: 'COMMANDS' },
  { source: 'core', target: 'net-edge', relType: 'COMMANDS' },
  { source: 'core', target: 'health-iomt', relType: 'COMMANDS' },
  { source: 'core', target: 'automotive-v2x', relType: 'COMMANDS' },

  // Pillar to Agents / Tasks / Humans
  { source: 'industrial-ot', target: 'anomaly-ai', relType: 'OVERSEES' },
  { source: 'industrial-ot', target: 'plc-audit', relType: 'OVERSEES' },
  { source: 'industrial-ot', target: 'ot-eng', relType: 'OVERSEES' },

  { source: 'smart-bldg', target: 'tamper-ai', relType: 'OVERSEES' },
  { source: 'smart-bldg', target: 'port-scan', relType: 'OVERSEES' },
  { source: 'smart-bldg', target: 'zero-trust', relType: 'OVERSEES' },

  { source: 'net-edge', target: 'firmware-ai', relType: 'OVERSEES' },
  { source: 'net-edge', target: 'ota-patch', relType: 'OVERSEES' },
  { source: 'net-edge', target: 'pcap-stream', relType: 'OVERSEES' },

  { source: 'health-iomt', target: 'pki-sentinel', relType: 'OVERSEES' },
  { source: 'health-iomt', target: 'mqtt-audit', relType: 'OVERSEES' },

  { source: 'automotive-v2x', target: 'can-bus-ai', relType: 'OVERSEES' },
  { source: 'automotive-v2x', target: 'isolation-killswitch', relType: 'OVERSEES' },
  { source: 'automotive-v2x', target: 'soc-analyst', relType: 'OVERSEES' },

  // Agents/Tasks to Tools
  { source: 'anomaly-ai', target: 'suricata', relType: 'USES' },
  { source: 'anomaly-ai', target: 'wireshark', relType: 'USES' },
  { source: 'plc-audit', target: 'shodan', relType: 'USES' },
  { source: 'ot-eng', target: 'kibana', relType: 'USES' },
  { source: 'tamper-ai', target: 'kibana', relType: 'USES' },
  { source: 'port-scan', target: 'shodan', relType: 'USES' },
  { source: 'zero-trust', target: 'vault', relType: 'USES' },
  { source: 'firmware-ai', target: 'shodan', relType: 'USES' },
  { source: 'ota-patch', target: 'vault', relType: 'USES' },
  { source: 'pcap-stream', target: 'zeek', relType: 'USES' },
  { source: 'pcap-stream', target: 'wireshark', relType: 'USES' },
  { source: 'pki-sentinel', target: 'vault', relType: 'USES' },
  { source: 'mqtt-audit', target: 'zeek', relType: 'USES' },
  { source: 'can-bus-ai', target: 'suricata', relType: 'USES' },
  { source: 'isolation-killswitch', target: 'kibana', relType: 'USES' },
  { source: 'soc-analyst', target: 'kibana', relType: 'USES' },
];
